remove using sycl::fmax and using sycl::fmin
    it causes problems with new versions of dpcpp compiler:
    /common/sys/sycl.h:34:13: error: target of using declaration conflicts with declaration already in scope
       34 | using sycl::fmax;