Add constexpr to constants
This allows statements like:
constexpr float seven_times_pi = 7.f * float(pi);
to work properly, which previously didn't (instead gave: "error C2131: expression did not evaluate to a constant").

I see a few points for discussion here that might preclude it:
1.) Requires C++11
2.) May make some esoteric cases I'm not familiar with fail.

I just thought I'd put it out there for discussion.